### ISSUE TITLE
Downloads Routerアドオンとの競合

### ISSUE THREAD

**Issue by frolex98** [furyutei/twOpenOriginalImage#1]
はじめまして。大変便利に使わせていただいております。

私の環境ではDownloads Routerというアドオンを併用して保存先を自動で別のディレクトリに流しているのですが、11月9日のアップデートからDownloads Routerが

> この拡張機能は、ダウンロード ファイル「」に名前を付けることができませんでした。別の拡張機能（Twitter 原寸びゅー）が異なるファイル名「」を指定しました。

というエラーを吐くようになり、画像の保存先がブラウザの設定項目で指定したディレクトリに固定されるようになってしまいました。

できるだけルートには直接保存したくないので、最新のアップデートの目玉に水を指すような要望で恐縮ですが、何らかの対応をお願いいたします。

**Comment by furyutei** [comment]
ご報告ありがとうございます。
0.1.7.1702にて改善されているかと思いますので、お試し願います。

**Comment by frolex98** [comment]
0.1.7.1702にて解決していることを確認しました。
素早く対応して頂きありがとうございました。
