### ISSUE TITLE
Does not work for embedded tweets

### ISSUE THREAD

**Issue by daeeun** [furyutei/twOpenOriginalImage#10]
I am currently using the Chrome extension. Whenever I click image thumbnails in embedded tweets, the images show up just as if I did not install this extension.

![스크린샷 2019-08-10 오후 6 20 07](https://user-images.githubusercontent.com/7974888/62820211-e8b4d180-bb9b-11e9-9119-a24487819157.png)
![스크린샷 2019-08-10 오후 6 20 20](https://user-images.githubusercontent.com/7974888/62820214-ec485880-bb9b-11e9-8a2b-bcff7db5ede0.png)

**Comment by furyutei** [comment]
Up to version 0.1.8.500 did not support image display in quoted tweets.
Since it corresponds from 0.1.8.600, please try.

**Comment by daeeun** [comment]
Now it works well. Thanks!
Besides, I really appreciate your work, since it improves my twitter life a lot!
