### ISSUE TITLE
Question/Suggestion: PNG+Large > JPG+Orig

### ISSUE THREAD

**Issue by jwshields** [furyutei/twOpenOriginalImage#13]
Hello,

First off, thank you for this extension, it is much appreciated.

Some time ago, Twitter started converting PNGs to JPG format.
This caused changes how images are handled, uploaded PNGs were converted to JPG based on a set of criteria.

I've found an oddity that I think this suggestion may help with.

Example Tweet:
https://twitter.com/chaosanix/status/1247528748456402945

Image:
jpg-large: ~230KB - https://pbs.twimg.com/media/EVAcxrfU0AIaKIJ?format=jpg&name=large
jpg-orig: ~230KB - https://pbs.twimg.com/media/EVAcxrfU0AIaKIJ?format=jpg&name=orig
png-large: ~1.4MB - https://pbs.twimg.com/media/EVAcxrfU0AIaKIJ?format=png&name=large
png-orig: HTTP404

The extension automatically changes jpg-large to jpg-orig;
From what I have seen, jpg-large and jpg-orig are almost always similar in size, while the png-large is much larger/better quality than the JPG version.

Suggestion:
Would it be possible to test for png-large and redirect there instead of jpg-orig (if the PNG exists and/or is larger in terms of pixels or bytes?)

**Comment by squaresmile** [comment]
The png-large and jpg-orig images are pixel for pixel identical. Twitter probably only coverts the jpg-orig to png-large for compatibility purposes.
