### ISSUE TITLE
When clicking on an image the timeline resets to the top

### ISSUE THREAD

**Issue by SHOWTEX** [furyutei/twOpenOriginalImage#17]
Seems like its a new issue, havent had this before.

**Comment by yms0719** [comment]
I am having the same issue. It worked just fine days ago.

**Comment by furyutei** [comment]
The problem was caused by a change in Twitter's behavior.
It should be fixed in [version 0.1.8.1401](https://github.com/furyutei/twOpenOriginalImage/commit/aac12327eca004ae9d3b584cee8cf8530f22e4ee).
