### ISSUE TITLE
Every time when I exit the original picture window I will be back to the top of timeline

### ISSUE THREAD

**Issue by dothacker** [furyutei/twOpenOriginalImage#18]
Seems after recent update I notice every time I exit the original picture window I will be back to the top of timeline.
There are many similar comment on add-on page. https://addons.mozilla.org/en-US/firefox/addon/twitter-gensun-view/reviews/
I wonder this problem is triggered by Firefox or latest update.

**Comment by furyutei** [comment]
I think this bug has been fixed in version 0.1.8.1401 or later.
Please check the version, and if it is old, update & reload and try again.

**Comment by dothacker** [comment]
> 
> 
> I think this bug has been fixed in version 0.1.8.1401 or later.
> Please check the version, and if it is old, update & reload and try again.

Thanks. After update it works as expected. I should check the update firstly. And it's a fantastic add-on, keeping going.
