### ISSUE TITLE
Buttons on Tweets disappeared/Clicking on Image no longer opens original

### ISSUE THREAD

**Issue by Latias4Ever** [furyutei/twOpenOriginalImage#19]
Clicking on an image now opens the original "id/photo/1" link, instead of opening the image over the page and giving you the download button.

At the same time, the buttons to open the original or download the image (or video) have disappeared from the bottom of tweets.

![image](https://user-images.githubusercontent.com/24550309/132746796-d96405e3-aa5f-43e0-89c1-18b045ab2163.png)

This was oddly working even today, so perhaps an update on Twitter's backend broke the extension.

**Comment by sukerokushin** [comment]
should be fixed now, an update was pushed ~11h ago

**Comment by Latias4Ever** [comment]
Yup, it's been fixed since that update. Closing.
