### ISSUE TITLE
TLでの原寸設定は機能していない

### ISSUE THREAD

**Issue by sukerokushin** [furyutei/twOpenOriginalImage#20]
（日本語は母国語ではないので日本語力がまだ弱くてすみません）
（でも少し自信があるんだから日本語で書いて試しています）

0.1.8.1601のアップデートは普通の機能に直してて感謝です。

だが、タイトル通り、TLの原寸設定は現在機能していないです。

例をあげます
![image](https://user-images.githubusercontent.com/55974345/132862002-1c5e30e8-14bc-43d7-b6f8-d06cd85e045b.png)
![image](https://user-images.githubusercontent.com/55974345/132862178-2c4e587f-2771-4e24-b787-9cd50d13ecde.png)

**Comment by furyutei** [comment]
I don't really understand the situation.

In my environment, it seems to work for both single tweets like
https://twitter.com/sukerokushin/status/1420972732179750912
and timelines like
https://twitter.com/sukerokushin

Can you give me an example of the specific URL that causes the problem and the details of the problem that occurs?

**Comment by sukerokushin** [comment]
oh i see, i decided to look at the only other extension that i had that could change things like this [and it was actually its fault.](https://github.com/Bl4Cc4t/GoodTwitter2/issues/345)
sorry for the confusion!
