### ISSUE TITLE
Firefox アドオンで、タイムラインが不意に一番上まで勝手にスクロールしてしまう

### ISSUE THREAD

**Issue by furyutei** [furyutei/twOpenOriginalImage#3]
https://twitter.com/mkaneda/status/931843951794909185
| Twitterのページ最上部に新しいツイートを見るってリンクがある状態で、Twitter原寸びゅーで、画像をオーバーレイで表示して、マウスホイールをまわすと裏のTwitterが一番上までスクロールされてる。

自分の環境では現象再現せず、様子見中。

**Comment by wyatt8740** [comment]
This is happening to me, now. It wasn't happening a week ago.
SeaMonkey 2.53.5.1, Greasemonkey 3.

**Comment by furyutei** [comment]
> This is happening to me, now. It wasn't happening a week ago.

The problem was caused by a recent change in Twitter's behavior.
It should be fixed in version [0.1.8.1401](https://github.com/furyutei/twOpenOriginalImage/commit/aac12327eca004ae9d3b584cee8cf8530f22e4ee).

**Comment by wyatt8740** [comment]
ありがとうございます。
